server:
  port: 8080

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/mon_association}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:root}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  # Clé de plus de 32 caractères (>= 256 bits)
  secret: ${JWT_SECRET:MonAssociationJwtSecretKey2026SuperSecurisee123456789}
  expiration-ms: ${JWT_EXPIRATION_MS:3600000}

admin:
  username: ${ADMIN_USERNAME:}
  email: ${ADMIN_EMAIL:}
  password: ${ADMIN_PASSWORD:}