server:
  port: 8080
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/mon_association}
    username: ${SPRING_DATASOURCE_USERNAME:assoc_user}
    password: ${SPRING_DATASOURCE_PASSWORD:change_me}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# JWT and security properties will be added later
